############################################################
@local = https://localhost:6999
@deploy = https://

############################################################
### local test requests
POST {{local}}/test
content-type: application/json

{
    "cargo": "ping"
}

############################################################
### deployment requests
POST {{deploy}}/route
content-type: application/json

{
}